version: '3.8'

services:

  db:
    image: docker.io/library/postgres  # La imagen de Docker oficial de PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  zookeeper:
    image: zookeeper:3.4.9
    restart: always
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./kafka/data/zookeeper/data:/data
      - ./kafka/data/zookeeper/datalog:/datalog
  kafka:
    image: confluentinc/cp-kafka:5.3.0
    restart: always
    hostname: kafka
    ports:
      - '9091:9091'
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG4J_ROOT_LOGLEVEL: ERROR
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      KAFKA_LOG4J_LOGGERS: "org.apache.zookeeper=ERROR,\
        org.apache.kafka=ERROR,\
        kafka=ERROR,\
        kafka.cluster=ERROR,\
        kafka.controller=ERROR,\
        kafka.coordinator=ERROR,\
        kafka.log=ERROR,\
        kafka.server=ERROR,\
        kafka.zookeeper=ERROR,\
        state.change.logger=ERROR,\
        kafka.log.LogCleaner=ERROR"
    volumes:
      - ./kafka/data/kafka/data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: always
    ports:
      - '9099:9000'
    environment:
      KAFKA_BROKERCONNECT: 'kafka:19091'
    depends_on:
      - kafka
